# Generated by Django 4.2.1 on 2023-05-15 02:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(help_text='Enter The Course Title At Least 10 Words', max_length=30)),
                ('course_slug', models.SlugField(unique=True)),
                ('course_about', models.CharField(help_text='Enter The Course Details At Least 20 Words', max_length=100)),
                ('what_we_learn', ckeditor.fields.RichTextField()),
                ('course_thumbnail', models.ImageField(upload_to='static/upload/')),
                ('course_join', models.DateTimeField(auto_now_add=True)),
                ('course_price', models.IntegerField()),
                ('course_discount', models.IntegerField(default=0, help_text='Enter The Discount In Percentage Like 25,75 etc.')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='PremiumCourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('article', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.premiumcourse')),
            ],
            options={
                'verbose_name_plural': 'Course Detail',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', editable=False, max_length=254)),
                ('provider_order_id', models.CharField(editable=False, max_length=254, verbose_name='Order ID')),
                ('payment_id', models.CharField(editable=False, max_length=254)),
                ('signature_id', models.CharField(editable=False, max_length=254)),
                ('amount', models.IntegerField(editable=False)),
                ('order_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='premium.premiumcourse')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(editable=False)),
                ('say_something', models.TextField(editable=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='premium.premiumcourse')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='static/upload/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.premiumcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
